import { Directory, File, Paths } from 'expo-file-system';

import type { PageNarration, Story, StoryNarrationSummary } from '@/types/story';

/**
 * Narration resolution — the heart of the hybrid recorded/cloned model.
 *
 * Every story page has one audio slot per voice profile. It is filled by,
 * in order of preference:
 *   1. a real recording made by the profile owner  → kind 'recorded'
 *   2. cloned TTS in the owner's voice (future)    → kind 'cloned'
 *   3. nothing yet                                 → kind 'none'
 *
 * Recordings live on-device under:
 *   <documents>/recordings/<profileId>/<storyId>/page-<n>.m4a
 */

function storyDir(profileId: string, storyId: string): Directory {
  return new Directory(Paths.document, 'recordings', profileId, storyId);
}

export function pageRecordingFile(profileId: string, storyId: string, pageIndex: number): File {
  return new File(storyDir(profileId, storyId), `page-${pageIndex}.m4a`);
}

export async function savePageRecording(
  profileId: string,
  storyId: string,
  pageIndex: number,
  sourceUri: string
): Promise<string> {
  const dir = storyDir(profileId, storyId);
  dir.create({ intermediates: true, idempotent: true });

  const dest = pageRecordingFile(profileId, storyId, pageIndex);
  if (dest.exists) {
    dest.delete();
  }
  await new File(sourceUri).copy(dest);
  return dest.uri;
}

export function deletePageRecording(profileId: string, storyId: string, pageIndex: number): void {
  const file = pageRecordingFile(profileId, storyId, pageIndex);
  if (file.exists) {
    file.delete();
  }
}

export function getPageNarration(
  profileId: string | null,
  storyId: string,
  pageIndex: number
): PageNarration {
  if (!profileId) {
    return { kind: 'none', uri: null };
  }
  const recording = pageRecordingFile(profileId, storyId, pageIndex);
  if (recording.exists) {
    return { kind: 'recorded', uri: recording.uri };
  }
  // Future: fall back to cloned TTS audio generated by the profile's voice
  // model, returning { kind: 'cloned', uri } so the UI can label the source.
  return { kind: 'none', uri: null };
}

export function getStoryNarration(profileId: string | null, story: Story): PageNarration[] {
  return story.pages.map((_, index) => getPageNarration(profileId, story.id, index));
}

export function summarizeStory(profileId: string | null, story: Story): StoryNarrationSummary {
  const narrations = getStoryNarration(profileId, story);
  const recordedPages = narrations.filter((n) => n.kind === 'recorded').length;
  const totalPages = story.pages.length;
  return {
    recordedPages,
    totalPages,
    status: recordedPages === 0 ? 'none' : recordedPages === totalPages ? 'complete' : 'partial',
  };
}
